name: x86 Make CI

on: ['push']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install openssl nad valgrind for running test script
      run:  sudo apt install openssl valgrind
    - name: install mbedtls
      run:  sudo apt install libmbedtls-dev
    - name: build with mbedtls
      run: make secvarctl-cov
    - name: test mbedtls build
      run: |
        cd test
        make MEMCHECK=1
        make clean
        cd ..
        make clean
        
    - name: install  openssl-libs
      run:  sudo apt install  libssl-dev
    - name: build with openssl
      run: make OPENSSL=1 secvarctl-cov
    - name: test openssl build
      run: |
        cd test
        make OPENSSL=1 MEMCHECK=1
        make clean
        cd ..
        make clean
    
    - name: run and test cmake builds
      run: |
        sudo apt install cmake
        mkdir build
        cd build
        cmake ../ .
        cmake --build .
        mv  secvarctl ../secvarctl-cov
        cd ../test
        make
        make clean 
        cd ../build
        rm -r *
        cmake ../ -DOPENSSL=1 .
        cmake --build .
        mv  secvarctl ../secvarctl-cov
        cd ../test
        make OPENSSL=1
        make clean
        cd ..
        
  
